In [1]:
print("hello")

hello


# **Introduction to numpy**

In [2]:
import numpy as np
a = np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
L = range(1000)
%timeit [i**2 for i in L]

1000 loops, best of 5: 246 µs per loop


In [4]:
a = np.arange(1000)
%timeit a**2

The slowest run took 2111.65 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.38 µs per loop


`As seen from above, Numpy is more memory efficient than normal list`

## 1. Creation of Arrays

---


### 1.1 Manual construction of arrays

In [5]:
# 1D Array
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [6]:
# Number of dimesnions
a.ndim

1

In [7]:
# Shape
a.shape

(4,)

In [8]:
# Length
len(a)

4

In [9]:
# 2D Array
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim # dimesnions

2

In [11]:
b.shape # shape

(2, 3)

In [12]:
len(b) # size of first dimension

2

In [14]:
# 3D Array
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
c.ndim

3

In [16]:
c.shape

(2, 2, 2)

In [17]:
len(c)

2

### 1.2 Function for creating arrays

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(1,10,2) # using start, end (exclusive), step
b

array([1, 3, 5, 7, 9])

In [19]:
a = np.linspace(0,1,6) # start, end, nb of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
# common arrays
a = np.ones((3,2 ,4)) # create 3 dim arrays
print(a)

print(a.ndim)
print(a.shape)
print(len(a))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
(3, 2, 4)
3


In [21]:
b = np.zeros((2,4,3))
print(b)
print("*******")
print(b.ndim)
print("*******")
print(b.shape)
print("*******")
print(len(b))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
*******
3
*******
(2, 4, 3)
*******
2


In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
d = np.eye(3,2) # 3 rows and 2 columns identical matrix
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [24]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
a = np.diag(range(10))
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [26]:
np.diag(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# create array using random
a = np.random.rand(4) # uniform random variables
a

array([0.6297567 , 0.65539904, 0.20253355, 0.73526536])

In [28]:
b = np.random.randn(4) # standard normal random variables
b

array([0.30214191, 0.45772914, 0.80415609, 0.75006824])

## 2. Basic Data Types

In [29]:
a = np.arange(10)
a.dtype

dtype('int64')

In [30]:
a = np.arange(10, dtype ='float64')
print(a)
a.dtype

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [31]:
b = np.zeros((2,3,4))
print(b)
b.dtype

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


dtype('float64')

In [32]:
d = np.array([1+2j, 2+4j])
print(d)
d.dtype

[1.+2.j 2.+4.j]


dtype('complex128')

In [33]:
e = np.array([True, False, False, True])
print(e)
e.dtype

[ True False False  True]


dtype('bool')

In [34]:
f = np.array(['Raja111','Ram'])
print(f)
f.dtype

['Raja111' 'Ram']


dtype('<U7')

## 3. Indexing and Slicing

### Indexing

In [35]:
a = np.arange(10)
print(a[5])

5


In [36]:
a = np.diag([1,2,3])
print(a)
print(a[2][2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [ ]:
a[2][1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

### Slicing

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Print even numbers
a[::2]

array([0, 2, 4, 6, 8])

In [39]:
# Print Odd numbers
a[1:10:2]

array([1, 3, 5, 7, 9])

In [40]:
a = np.arange(10)
print(a)
a[6:] = 11
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5 11 11 11 11]


In [41]:
b = np.arange(4)
print(a)
print(b)
a[6:] = b[::-1]
print(a)
print(b)

[ 0  1  2  3  4  5 11 11 11 11]
[0 1 2 3]
[0 1 2 3 4 5 3 2 1 0]
[0 1 2 3]


## 4. Copies and Views

In [42]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
b = a [::2]
b

array([0, 2, 4, 6, 8])

In [44]:
np.shares_memory(a,b)

True

In [45]:
b[0] = 10
print(b)
a

[10  2  4  6  8]


array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [46]:
np.shares_memory(a,b)

True

In [47]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [49]:
np.shares_memory(a,c)

False

In [50]:
c[0] = 10
print(a)
print(c)
np.shares_memory(a,c)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


False

In [51]:
a = np.arange(20)
print(a)
print(id(a))

b = a[::2]
print(b)
print(id(b))

np.shares_memory(a,b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
140573382181072
[ 0  2  4  6  8 10 12 14 16 18]
140573381857968


True

In [ ]:
# Python code to demonstrate copy operations

# importing "copy" for copy operations
import copy

# initializing list 1
li1 = [1, 2, [3,5], 4]

# using deepcopy to deep copy
li2 = copy.deepcopy(li1)

# original elements of list
print ("The original elements before deep copying")
for i in range(0,len(li1)):
	print (li1[i],end=" ")

print("\r")

# adding and element to new list
li2[2][0] = 7

# Change is reflected in l2
print ("The new list of elements after deep copying ")
for i in range(0,len( li2)):
	print (li2[i],end=" ")

print("\r")

# Change is NOT reflected in original list
# as it is a deep copy
print ("The original elements after deep copying")
for i in range(0,len( li1)):
	print (li1[i],end=" ")


The original elements before deep copying
1 2 [3, 5] 4 
The new list of elements after deep copying 
1 2 [7, 5] 4 
The original elements after deep copying
1 2 [3, 5] 4 

In [ ]:
# Python code to demonstrate copy operations

# importing "copy" for copy operations
import copy

# initializing list 1
li1 = [1, 2, [3,5], 4]

# using copy to shallow copy
li2 = copy.copy(li1)

# original elements of list
print ("The original elements before shallow copying")
for i in range(0,len(li1)):
	print (li1[i],end=" ")

print("\r")

# adding and element to new list
li2[2][0] = 7

# checking if change is reflected
print ("The original elements after shallow copying")
for i in range(0,len( li1)):
	print (li1[i],end=" ")


The original elements before shallow copying
1 2 [3, 5] 4 
The original elements after shallow copying
1 2 [7, 5] 4 

##5. Fancy Indexing

In [56]:
a = np.random.randint(0, 30,20)
print(a)

[16 28 26 17 22 10  6 27  5  6 28 20 27  6  8 25 23 29  2 18]


In [57]:
mask = (a % 2 == 0)
mask

array([ True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True,  True])

In [58]:
extract_from_a = a[mask]
extract_from_a

array([16, 28, 26, 22, 10,  6,  6, 28, 20,  6,  8,  2, 18])

In [59]:
np.shares_memory(a, extract_from_a)

False

In [60]:
a[mask] = -1
print(a)
print(extract_from_a)

[-1 -1 -1 17 -1 -1 -1 27  5 -1 -1 -1 27 -1 -1 25 23 29 -1 -1]
[16 28 26 22 10  6  6 28 20  6  8  2 18]


In [61]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [63]:
a[[9,7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

# **Numerical Operations on numpy**

## **Element wise Operations**

### **Basic Operations**

**Scalars**

In [64]:
a = np.array([1,2,3,4,5])
a+1

array([2, 3, 4, 5, 6])

In [65]:
a**2

array([ 1,  4,  9, 16, 25])

**Arithmetic Operations elementwise**

In [66]:
b = np.ones(5)+1
b

array([2., 2., 2., 2., 2.])

In [67]:
a-b

array([-1.,  0.,  1.,  2.,  3.])

In [68]:
a*b

array([ 2.,  4.,  6.,  8., 10.])

**Matrix Multiplication**

In [69]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
print(c*c)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [71]:
print(c.dot(c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


**Comparisions**

In [73]:
a= np.array([1,2,3,4])
b= np.array([5,2,2,4])

a==b

array([False,  True, False,  True])

In [74]:
a>b

array([False, False,  True, False])

In [75]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [76]:
np.array_equal(a,b)

False

In [77]:
np.array_equal(c,a)

True

**Logical Operations**

In [79]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

In [80]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [81]:
np.logical_and(b,a)

array([ True, False, False, False])

**Transcendental functions**

In [82]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [83]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [84]:
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [85]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape Mismatch**

In [86]:
a = np.arange(4)
a + np.array([1,2])

ValueError: ignored

## Basic Reductions

### **Computing Sums**

In [87]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [88]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [89]:
x.sum(axis=0) # column sums

array([4, 6])

In [90]:
x.sum(axis=1) # row sum

array([3, 7])

### **Other Reductions**

In [91]:
x = np.array([1,2,3,4])
x.min()

1

In [92]:
x.max()

4

In [93]:
x.argmin()

0

In [94]:
x.argmax()

3

### **Logical Operations**

In [95]:
np.all([True, True, False])

False

In [96]:
np.all([1,1,1])

True

In [97]:
np.any([True, False, False])

True

In [98]:
np.any([1,0,0])

True

In [99]:
a = np.zeros((50,50))

In [100]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [101]:
np.any(a!=0)

False

In [102]:
np.all(a==a)

True

In [104]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])

((a<=b) & (b<=c)).all()

True

### **Statistics**

In [108]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])


In [105]:
x.mean()

2.5

In [106]:
np.median(x)

2.5

In [109]:
np.median(y, axis=0)

array([3., 4., 2.])

In [111]:
np.median(y, axis=1)

array([2., 5.])

In [112]:
x.std()

0.82915619758885

In [113]:
import os
os.chdir('/content/drive/MyDrive/Colab Notebooks')
data = np.loadtxt('populations.txt')

In [114]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [115]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [116]:
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [117]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [120]:
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

## **Broadcasting**

In [121]:
a = np.tile(np.arange(0,40,10),(3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [122]:
a=a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [123]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [124]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [125]:
a = np.arange(0,40, 10)
a

array([ 0, 10, 20, 30])

In [126]:
a.shape

(4,)

In [127]:
a = a[: , np.newaxis]
a.shape

(4, 1)

In [128]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [129]:
b

array([0, 1, 2])

In [131]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### **Array Shape Manipulation**

### Flattening

In [132]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [133]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [135]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

### Reshaping

In [136]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
a.shape

(2, 3)

In [138]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [139]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
b[0][0] = 100

In [141]:
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [142]:
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [143]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [144]:
b = a.T.reshape(3*2)
b

array([0., 0., 0., 0., 0., 0.])

In [145]:
b[0] = 50
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [146]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Adding a dimension

In [147]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [148]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [149]:
a = np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

### **Resizing**

In [150]:
a = np.arange(4)
a.resize(8)
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [151]:
b =a
a.resize(4)

ValueError: ignored

### **Sorting**

In [152]:
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [153]:
a.sort(axis=1)

In [154]:
a

array([[4, 5, 6],
       [2, 2, 3]])

In [155]:
a = np.array([4,3,1,2])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [156]:
a[j]

array([1, 2, 3, 4])